# Generated by Django 4.2.8 on 2024-03-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('room', '0002_alter_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Hotel'),
        ),
    ]
